### ISSUE TITLE
Not a directory: './trained/CHOGRGB4.pkl'

### ISSUE THREAD

**Issue by molyswu** [diyjac/SDC-P5#2]
Hi,
python3 P5pipeline.py test_images/test1.jpg output_images/test1.jpg

Camera Calibration data restored from camera_cal/calibrationdata.p
Traceback (most recent call last):
  File "P5pipeline.py", line 218, in <module>
    roadMgr = RoadManager(camCal, debug=debug, scrType=scrType)
  File "/mnt/hgfs/study/123/Vehicle-Detection/SDC-P5/p5lib/roadManager.py", line 130, in __init__
    self.threshold)
  File "/mnt/hgfs/study/123/Vehicle-Detection/SDC-P5/p5lib/vehicleDetection.py", line 44, in __init__
    self.svc = joblib.load(self.trained_model)
  File "/usr/local/lib/python3.5/dist-packages/sklearn/externals/joblib/numpy_pickle.py", line 570, in load
    with open(filename, 'rb') as f:
NotADirectoryError: [Errno 20] Not a directory: './trained/CHOGRGB4.pkl'
Tank you!

**Comment by diyjac** [comment]
Hi molyswu,

Can you verify that the symbolic link to the trained directory under https://github.com/diyjac/SDC-P5/blob/master/trained points to https://github.com/diyjac/SDC-P5/tree/master/vehicleLab/trained in your set up?  Cheers, John.

**Comment by osa3301** [comment]
same issue, yes it points, what to do ?
